### ISSUE TITLE
Failed to load the hidpi package

### ISSUE THREAD

**Issue by johnrobharrison** [mcanders/atom-hidpi#16]
[Enter steps to reproduce below:]
Just trying to install hidpi package on an Arch Linux system.

**Atom Version**: 1.10.2
**Electron Version**: 1.3.5
**System**: linux 4.7.2-1-ARCH
**Thrown From**: [hidpi](https://github.com/mcanders/atom-hidpi) package, v0.11.0
### Stack Trace

Failed to load the hidpi package

```
At Cannot find module 'web-frame'

Error: Cannot find module 'web-frame'
  at Module._resolveFilename (module.js:440:15)
  at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:383:52)
  at Function.Module._load (module.js:388:25)
  at Object.<anonymous> (/home/shinsters/.atom/packages/hidpi/lib/hidpi.coffee:2:12)
  at Object.<anonymous> (/home/shinsters/.atom/packages/hidpi/lib/hidpi.coffee:1:1)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Package.module.exports.Package.requireMainModule (/usr/lib/atom/src/package.js:718:27)
  at /usr/lib/atom/src/package.js:117:28
  at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:92:15)
  at Package.module.exports.Package.load (/usr/lib/atom/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/lib/atom/src/package-manager.js:449:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:528:30)
  at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:460:29
  at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:215:47)
  at /usr/lib/atom/src/buffered-process.js:229:18
  at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:100:18)
  at emitOne (events.js:101:20)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:492:12)

```
### Commands

```
     -3:26.5.0 application:add-project-folder (atom-pane.pane.active)
     -1:31 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:27.7.0 key-binding-resolver:toggle (atom-pane.pane.active)
     -1:27.3.0 settings-view:open (atom-pane.pane.active)
     -1:18.8.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -1:16.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -1:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
hidpi, v0.11.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by cart** [comment]
WebFrame is a part of electron and isn't something my package sets up or configures.  I am guessing you somehow have a bad atom or electron install.  I am running a similar setup to yours (Arch, linux 4.7.2, atom 1.11 beta) and mine works fine.  Are you installing atom from an AUR package?  If you tell me which one I can test it.  Or maybe try installing "aur/atom-editor-beta"?  It works wonderfully for me.

**Comment by rspears74** [comment]
I have the same issue. Exact same versions of everything. Exact same stack trace.

**Comment by cart** [comment]
I am unable to reproduce this with "aur/atom-editor" (which corresponds to atom 1.10.2).  Is that the package you are using?

**Comment by rspears74** [comment]
Im using the package from the community repository. Ill try the AUR package.

**Comment by photomattmills** [comment]
I'm having a similar error, except failing to find 'electron'. Seems odd, since that's a core package, right?

1. install package
2. that's it, the error happens (and also happens on startup every time)

**Atom Version**: 1.6.2
**System**: Ubuntu 16.04.2
**Thrown From**: [hidpi](https://github.com/mcanders/atom-hidpi) package, v0.12.0


### Stack Trace

Failed to load the hidpi package

```
At Cannot find module 'electron'

Error: Cannot find module 'electron'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/matt/.atom/packages/hidpi/lib/hidpi.coffee:2:12)
    at Object.<anonymous> (/home/matt/.atom/packages/hidpi/lib/hidpi.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at /usr/share/atom/resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hidpi, v0.12.0
language-elixir, v0.12.3

# Dev
No dev packages
```
